services:
  db:
    image: postgres:15-alpine
    container_name: minierp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sainik@6338
      POSTGRES_DB: minierp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: